GET http://localhost:3000

###
GET http://localhost:3000/post/67487f24e9a8933548f3ddc2

###
GET http://localhost:3000/post?sender=TestOwner

###
POST http://localhost:3000
Content-Type: application/json

{
    "owner": "KimK",
    "title": "The Best Post",
    "content": "This is my first post"
}

###
PUT http://localhost:3000/post/67700545a15ccc9c652e2c20
Content-Type: application/json

{
    "owner": "lulu"
}

###
GET http://localhost:3000/comment

###
POST http://localhost:3000/comment
Content-Type: application/json

{
    "author": "David",
    "content": "Wow",
    "postId": "67700b72bfef40e16227b228"
}

###
GET http://localhost:3000/comment/67700b72bfef40e16227b22d

###
PUT http://localhost:3000/comment/674e3076acd2b21103886fcf
Content-Type: application/json

{
    "author": "David",
    "content": "Amazing Post!"
}

###
DELETE http://localhost:3000/comment/674e2ccec42eddc393fd4420