GET http://localhost:3000/posts

###
GET http://localhost:3000/posts/677140f2d3840dc5cf439929

###
GET http://localhost:3000/posts?sender=KimK

###
POST http://localhost:3000/posts
Authorization: 'JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NzdhNjY5NzQyODkxNDU0Zjk3OWU2M2UiLCJyYW5kb20iOiIwLjQyNTM1MzEwNzkxNzEzOTU0IiwiaWF0IjoxNzM2MDc1MTYyLCJleHAiOjE3MzYwODU5NjJ9.CQbuN4eJwCkAoKAKVX29EZyI3VVBHv4omrehj1oekJM',

{
    "owner": "KimK",
    "title": "The Best Post",
    "content": "This is my first post"
}

###
DELETE http://localhost:3000/post/677140f2d3840dc5cf439929

###
GET http://localhost:3000/comments

###
POST http://localhost:3000/comments
Content-Type: application/json

{
    "author": "David",
    "content": "Wow",
    "postId": "67712fecdbb84f4b57182d8e"
}

###
GET http://localhost:3000/comment/

###
GET http://localhost:3000/comment/674888aaa1a6b39541835fe0

###
PUT http://localhost:3000/comment/674e3076acd2b21103886fcf
Content-Type: application/json

{
    "author": "David",
    "content": "Amazing Post!"
}

###
DELETE http://localhost:3000/comment/674e2ccec42eddc393fd4420

###
GET http://localhost:3000/users

###
POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "email": "Kim@gmail.com",
    "password": "password"
}

###
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "Kim@gmail.com",
    "password": "password"
}

###
POST http://localhost:3000/auth/refresh
Content-Type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NzdhNzE5NTRhZjk2OTZmMDI2ODVjOTgiLCJyYW5kb20iOiIwLjMzNzE3NDM2NTM0MzExNTYiLCJpYXQiOjE3MzYwNzc3MTksImV4cCI6MTczNjY4MjUxOX0.Kl0dreF1ZBMhK2Cuf4uojfr4HyD60LAZ8TBFZ-iMdww"
}